version: 2.1
orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.1.3
jobs:
  coverage:
    docker:
      - image: cimg/node:15.4.0
    steps:
      - codecov/upload:
        file: './coverage/clover.xml'
workflows:
  test:
    jobs:
      - node/test
      - coverage