version: 2.1
orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.1.3
jobs:
  coverage:
    steps:
      - codecov/upload:
        file: './coverage/clover.xml'
workflows:
  test:
    jobs:
      - node/test
      - coverage